import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" >
      <body >
        <header className="fixed top-0 left-0 right-0 z-50 bg-slate-900 border-b border-slate-800">
          <nav className="max-w-7xl mx-auto px-6 h-24 grid grid-cols-3 items-center">

            <div className="flex justify-start">
              <Link href="/" className="hover:text-gray-300 font-bold tracking-tight border border-slate-500 rounded-md px-5 py-1">
                Home
              </Link>
            </div>

            <div className="flex flex-col items-center justify-center space-y-1">
              <Image 
                src="/AssetHub-logo.png" 
                alt="AssetHub Logo" 
                width={40} 
                height={40} 
              />
              <span className="font-bold tracking-tight text-sm uppercase">AssetHub</span>
            </div>

            <div className="flex justify-end space-x-4">
              <Link href="/login" className="hover:text-gray-300 font-bold tracking-tight border border-slate-500 rounded-md px-5 py-1">
                Login
              </Link>
              <Link href="/register" className="hover:text-gray-300 font-bold tracking-tight border border-slate-500 rounded-md px-5 py-1">
                Register
              </Link>
            </div>

          </nav>
        </header>
        
          {children}
        

        <footer className="px-6 py-12 border-t border-slate-900 text-center">
        <div className="flex items-center justify-center gap-2 mb-4">
          <Image src="/AssetHub-logo.png" alt="AssetHub Logo" className=" w-auto m-auto" 
                width={30}
                height={24} 
          />
          
        </div>
        
        <span className="text-xl font-bold text-white tracking-tight">AssetHub</span>
        <p className="text-slate-500 text-sm mb-2">
          &copy; 2026 AssetHub Systems Inc. Built for the future of retail.
        </p>
        <div className="flex items-center justify-center gap-2 mb-2">
            <Link href="#" className="text-slate-500 text-sm mb-2 hover:text-gray-400">
              Privacy Policy
            </Link>
            <Link href="#" className="text-slate-500 text-sm mb-2 hover:text-gray-400">
              Terms of Service
            </Link>  
          </div>
          <div>
            <Link href="/about" className="text-slate-500 text-sm mb-2 hover:text-gray-400">
              About
            </Link>
          </div>
      </footer>
       
      </body>
    </html>
  );
}
