import type { Metadata } from "next";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";
import { AuthProvider } from './context/AuthContext';
import Navbar from "./components/navbar";
import Footer from "./components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { ReactNode } from "react";

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body className="bg-[#020617]">
        <AuthProvider>
          <Navbar />
          {/* pt-20 ensures content isn't hidden behind the fixed navbar */}
          <main className="pt-20">
            {children}
          </main>
        </AuthProvider>
        <Footer />
      </body>
    </html>
  );
}

